
export interface AllDataTypesDTO 
{
  id: number
  smallIntCol: number
  integerCol: number
  bigIntCol: number
  decimalCol: number
  numericCol: number
  realCol: number
  doublePrecisionCol: number
  smallSerialCol: number
  serialCol: number
  bigSerialCol: number
  moneyCol: string
  charCol: string
  varcharCol: string
  textCol: string
  byteaCol: Buffer
  dateCol: string
  timeCol: string
  timeWithTzCol: string
  timestampCol: string
  timestampWithTzCol: string
  intervalCol: string
  booleanCol: boolean
  uuidCol: string
  jsonCol: any
  jsonbCol: any
  xmlCol: string
  pointCol: string
  lineCol: string
  lsegCol: string
  boxCol: string
  pathCol: string
  polygonCol: string
  circleCol: string
  cidrCol: string
  inetCol: string
  macaddrCol: string
  bitCol: string
  varbitCol: string
  tsqueryCol: string
  tsvectorCol: string
  int4rangeCol: string
  int8rangeCol: string
  numrangeCol: string
  tsrangeCol: string
  tstzrangeCol: string
  daterangeCol: string
}
